[build]
  command = "mkdir -p public && touch public/index.html"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/welcome"
  status = 200
  force = true