[build]
  publish = "public"
  functions = "netlify/functions"

# This forces the root URL (/) to hit your Python function
[[redirects]]
  from = "/"
  to = "/.netlify/functions/welcome"
  status = 200
  force = true